### ISSUE TITLE
panic: reflect: NumField of non-struct type bool when onboot: true

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#1472]
### Steps to reproduce

```wwctl node list -a n1```

```
WW_INTERNAL: 43
nodeprofiles:
  default:
    comment: This profile is automatically included for each node
    container name: rocky-8
    system overlay:
    - wwinit
    - ifcfg
nodes:
  n1:
    comment: a node comment
    cluster name: mycluster
    kernel:
      args: crashkernel=no vga=791 net.naming-scheme=v238
    profiles:
    - default
    network devices:
      default:
        type: Ethernet
        onboot: true
        device: eth0
        hwaddr: a0:88:c2:03:00:d3
        ipaddr: 192.168.0.100
        netmask: 255.255.255.0
        gateway: 192.168.0.1
    tags:
      arch: x86_64
```

### Error message

```
panic: reflect: NumField of non-struct type bool

goroutine 1 [running]:
reflect.(*rtype).NumField(0x0?)
	/usr/lib/golang/src/reflect/type.go:762 +0x6c
github.com/warewulf/warewulf/internal/pkg/node.fieldMap.recursiveFields(0xf10340?, {0xf10340?, 0x4000313b0e?}, {0x400058d890, 0x18}, {0x0, 0x0})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/node/list.go:90 +0x18c
github.com/warewulf/warewulf/internal/pkg/node.fieldMap.recursiveFields(0x400061e050?, {0xfb6320?, 0x4000178410?}, {0x400058d878, 0x11}, {0x0, 0x0})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/node/list.go:118 +0x1388
github.com/warewulf/warewulf/internal/pkg/node.fieldMap.recursiveFields(0xff6340?, {0xff6340?, 0x40003de190?}, {0x0, 0x0}, {0x0, 0x0})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/node/list.go:106 +0x1a14
github.com/warewulf/warewulf/internal/pkg/node.fieldMap.recursiveFields(0xf9c8a0?, {0x1059280?, 0x40003de140?}, {0x0, 0x0}, {0x0, 0x0})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/node/list.go:115 +0x354
github.com/warewulf/warewulf/internal/pkg/node.(*NodeYaml).GetFields(_, {{0x4000312150, 0x2}, 0x1, {0x0, 0x0}, {0x0, 0x0}, {0x400036c350, 0x1, ...}, ...})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/node/list.go:51 +0x204
github.com/warewulf/warewulf/internal/pkg/api/node.NodeList(0x400061fbb0)
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/api/node/list.go:88 +0x13ac
github.com/warewulf/warewulf/internal/app/wwctl/node/list.GetCommand.CobraRunE.func2(0x400015ea00?, {0x400059b820?, 0x1?, 0x2?})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/app/wwctl/node/list/main.go:35 +0x13c
github.com/spf13/cobra.(*Command).execute(0x40005b2600, {0x400059b800, 0x2, 0x2})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/vendor/github.com/spf13/cobra/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1a6de40)
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/vendor/github.com/spf13/cobra/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(0x40000021a0?)
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/vendor/github.com/spf13/cobra/command.go:1039 +0x1c
main.main()
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/cmd/wwctl/main.go:13 +0x24
```

Also setting `onboot: "true"` fails, but with a different error.

```
$ sudo wwctl node list -a n1
ERROR: yaml: unmarshal errors:
  line 20: cannot unmarshal !!str `true` into bool
```

### Information on your system

```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
```

```
$ sudo wwctl version
wwctl version:	 4.5.1test1+369.g9fc3ab71.dirty-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.1test1+369.g9fc3ab71.dirty-1"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
@mslacken can you fix this? Not sure how this hasn't been picked up by the testsuite.

**Comment by anderbubble** [comment]
I'm realizing this is probably a result of me changing this to a pointer type; so I'll  take responsibility for it.
