### ISSUE TITLE
adding tag fails with a netdev

### ISSUE THREAD

**Issue by mslacken** [warewulf/warewulf#1546]
### Steps to reproduce

```wwctl node set n01 --tagadd GrubMenuEntry=dracut```

### Error message

```panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/warewulf/warewulf/internal/pkg/api/node.NodeSetParameterCheck(0xc00051fa18)
	/home/abuild/rpmbuild/BUILD/warewulf-0f66aec96080499c49ee0fac8bc63010a2fb4856/internal/pkg/api/node/set.go:138 +0x18c5
github.com/warewulf/warewulf/internal/app/wwctl/node/set.GetCommand.CobraRunE.func8(0xc0006f5800?, {0xc0000c43c0, 0x1, 0x3})
	/home/abuild/rpmbuild/BUILD/warewulf-0f66aec96080499c49ee0fac8bc63010a2fb4856/internal/app/wwctl/node/set/main.go:79 +0x9ca
github.com/spf13/cobra.(*Command).execute(0xc0006fe000, {0xc0000c4360, 0x3, 0x3})
	/home/abuild/rpmbuild/BUILD/warewulf-0f66aec96080499c49ee0fac8bc63010a2fb4856/vendor/github.com/spf13/cobra/command.go:985 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x56508c523420)
	/home/abuild/rpmbuild/BUILD/warewulf-0f66aec96080499c49ee0fac8bc63010a2fb4856/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0000061a0?)
	/home/abuild/rpmbuild/BUILD/warewulf-0f66aec96080499c49ee0fac8bc63010a2fb4856/vendor/github.com/spf13/cobra/command.go:1041 +0x13
main.main()
	/home/abuild/rpmbuild/BUILD/warewulf-0f66aec96080499c49ee0fac8bc63010a2fb4856/cmd/wwctl/main.go:13 +0x1e
```

### Information on your system

```
`nodeprofiles:
  default: {}
nodes:
  n01:
    network devices:
      default:
        ipaddr: 172.16.130.101
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by mslacken** [comment]
@anderbubble don't assign, merge #1547

**Comment by anderbubble** [comment]
I already see the PR; I just assigned so the metadata matches, since you've already done the PR.
