### ISSUE TITLE
warewulf.conf: ipaddr cannot be FQDN

### ISSUE THREAD

**Issue by kivel** [warewulf/warewulf#181]
### This is a potential feature request.
for load balancing purposes, it would be advantageous to specify the hostname, rather than the IP address.
Currently, the string is converted to int at the '.', which fails of course.
config:
```
ipaddr: gfa-boot.psi.ch
netmask: 255.255.255.0
```
error:
```
panic: strconv.Atoi: parsing "gfa-boot": invalid syntax

goroutine 1 [running]:
github.com/brotherpowers/ipsubnet.convertQuardsToInt({0xc000035080, 0x3, 0xcf4ef0})
	/go/src/warewulf/vendor/github.com/brotherpowers/ipsubnet/ip.go:28 +0x11a
github.com/brotherpowers/ipsubnet.(*Ip).GetIPAddressQuads(0x0)
	/go/src/warewulf/vendor/github.com/brotherpowers/ipsubnet/ipPortion.go:23 +0x3d
github.com/brotherpowers/ipsubnet.(*Ip).networkCalculation(0xc00059fb90, {0xcf4f3f, 0x2}, {0xcf4ef0, 0x1})
	/go/src/warewulf/vendor/github.com/brotherpowers/ipsubnet/networkPortion.go:25 +0x53
github.com/brotherpowers/ipsubnet.(*Ip).GetNetworkPortion(...)
	/go/src/warewulf/vendor/github.com/brotherpowers/ipsubnet/networkPortion.go:9
github.com/hpcng/warewulf/internal/pkg/warewulfconf.New()
	/go/src/warewulf/internal/pkg/warewulfconf/constructors.go:45 +0x3b1
github.com/hpcng/warewulf/internal/app/wwctl/server/start.CobraRunE(0x13e1f80, {0xcf5ad4, 0x1, 0x1})
	/go/src/warewulf/internal/app/wwctl/server/start/main.go:13 +0x5a
github.com/spf13/cobra.(*Command).execute(0x13e1f80, {0xc0004c1f40, 0x1, 0x1})
	/go/src/warewulf/vendor/github.com/spf13/cobra/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x13d9700)
	/go/src/warewulf/vendor/github.com/spf13/cobra/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/warewulf/vendor/github.com/spf13/cobra/command.go:895
main.main()
	/go/src/warewulf/cmd/wwctl/main.go:13 +0x25
```

**Comment by PaulCharlton** [comment]
@kivel  as you note, hostname resolution via DNS can serve as a simplistic load-balancing between the IP addresses the resolver provides;   there are other strategies such as anycast IP addresses or being able to make use of existing CDN technologies that already have a global scale-out
